package com.reports.reportmaker;

import java.math.BigDecimal;

/**
 * Represents data from one line in CSV, or node in XML.
 * Generated by {@link ReadFile#readDataFromCSV(String)}
 * and {@link ReadFile#readDataFromXML(String)}
 * <p>
 * Used to unify the output information from read files, for further
 * validation and error identification before writing to the database.
 */

class DataLineObj {

    /**
     * ID of client.
     */
    private String mClientID;
    /**
     * Request ID.
     */
    private String mRequestID;
    /**
     * Name of client.
     */
    private String mName;
    /**
     * Quentity od product.
     */
    private String mQuantity;
    /**
     * Price of product.
     */
    private String mPrice;
    /**
     * identification of a possible error.
     */
    private String mErrorIdent;

    /**
     * Constructor.
     *
     * @param clientID   ID of client
     * @param requestID  request ID
     * @param name       mName of client
     * @param quantity   mQuantity of product
     * @param price      mPrice of product
     * @param errorIdent identifier of a possible error
     *                   - contains information about the line
     *                   being read and the file mName
     */
    DataLineObj(final String clientID,
                final String requestID,
                final String name,
                final String quantity,
                final String price,
                final String errorIdent) {

        mClientID = clientID;
        mRequestID = requestID;
        mName = name;
        mQuantity = quantity;
        mPrice = price;
        mErrorIdent = errorIdent;
    }


    /**
     * validation of input data.
     *
     * @return returns the object {@link DataModel}
     * if the input data is correct, or null if any exception is detected
     */
    DataModel validateData() {

        try {
            //parse strings to correct formats
            //and delete white-spaces from mClientID
            String validateClientID = mClientID.replaceAll("\\s", "");
            long validateRequestID = Long.parseLong(mRequestID);
            int validateQuantity = Integer.parseInt(mQuantity);

            //save to database as a DECIMAL(7,2)
            BigDecimal validatePrice = new BigDecimal(mPrice);

            //checking if these values are within the varchar range
            if (validateClientID.length() > ConstDataClass.MAX_CHAR_IN_USER_ID) {
                throw new Exception("too long mClientID");
            }
            if (mName.length() > ConstDataClass.MAX_CHAR_IN_USER_NAME) {
                throw new Exception("too long mName of product");
            }

            return new DataModel(validateClientID,
                    validateRequestID,
                    mName,
                    validateQuantity,
                    validatePrice);

        } catch (Exception e) {
            //throw parse exception for wrong format data,
            //and too long value in varChar
            System.out.println(mRequestID + " probably wrong data format in: " + mErrorIdent);
            e.printStackTrace();
        }

        return null;
    }
}
